package com.icedoutshows.springboot.backend.apirest.controllers;

public class MessageHTML {

	
	public static final String TEMPLATE_MENSAJE="<!DOCTYPE html>\r\n"
			+ "<html lang=\"es\">\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Mi Página Web</title>\r\n"
			+ "    <style>\r\n"
			+ "        /* Estilos CSS opcionales para dar un aspecto más agradable */\r\n"
			+ "        body {\r\n"
			+ "            font-family: Arial, sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "            background-color: #f4f4f4;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        header {\r\n"
			+ "            background-color: #333;\r\n"
			+ "            color: white;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding: 1em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        main {\r\n"
			+ "            margin: 20px;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "\r\n"
			+ "    <header>\r\n"
			+ "        <h1>Iced Out Shows</h1>\r\n"
			+ "    </header>\r\n"
			+ "\r\n"
			+ "    <main>\r\n"
			+ "        <h2>Estás suscrito!</h2>\r\n"
			+ "        <p>Bienvenido a la newsletter. Te enviaremos un correo si existe algún descuento o sorteo. Muchas gracias por tu colaboración!.</p>\r\n"
			+ "        <!-- Agrega más contenido según sea necesario -->\r\n"
			+ "    </main>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>";
}
