package com.icedoutshows.springboot.backend.apirest.controllers;

public class MessageHTML {

	
	public static final String TEMPLATE_MENSAJE="<!DOCTYPE html>\r\n"
			+ "<html lang=\"es\">\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Mi Página Web</title>\r\n"
			+ "    <style>\r\n"
			+ "        /* Estilos CSS opcionales para dar un aspecto más agradable */\r\n"
			+ "        body {\r\n"
			+ "            font-family: Arial, sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "            background-color: #f4f4f4;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        header {\r\n"
			+ "            background-color: #333;\r\n"
			+ "            color: white;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding: 1em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        main {\r\n"
			+ "            margin: 20px;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "\r\n"
			+ "    <header>\r\n"
			+ "        <h1>Iced Out Shows</h1>\r\n"
			+ "    </header>\r\n"
			+ "\r\n"
			+ "    <main>\r\n"
			+ "        <h2>Estás suscrito!</h2>\r\n"
			+ "        <p>Bienvenido a la newsletter. Te enviaremos un correo si existe algún descuento o sorteo. Muchas gracias por tu colaboración!.</p>\r\n"
			+ "        <!-- Agrega más contenido según sea necesario -->\r\n"
			+ "    </main>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>";
	
	
	
	public static final String ENTRADA_CONFIRMACION="<!DOCTYPE html>\r\n"
			+ "<html lang=\"es\">\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Mi Página Web</title>\r\n"
			+ "    <style>\r\n"
			+ "        /* Estilos CSS opcionales para dar un aspecto más agradable */\r\n"
			+ "        body {\r\n"
			+ "            font-family: Arial, sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "            background-color: #f4f4f4;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        header {\r\n"
		
			+ "            color: white;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding: 1em;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        main {\r\n"
			+ "            margin: 20px;\r\n"
			+ "            text-align: center; /* Centra el contenido dentro de la tarjeta */\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .card {\r\n"
			+ "            border: 1px solid #ddd; /* Borde de la tarjeta */\r\n"
			+ "            padding: 20px; /* Espaciado interno de la tarjeta */\r\n"
			+ "            border-radius: 10px; /* Bordes redondeados de la tarjeta */\r\n"
			+ "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra de la tarjeta */\r\n"
			+ "            background-color: #12486B; /* Color de fondo de la tarjeta */\r\n"
			+ "            max-width: 400px; /* Ancho máximo de la tarjeta */\r\n"
			+ "            margin: auto; /* Centra la tarjeta en la página */\r\n"        
			+ "        }\r\n"
			+ "\r\n"
			+ "        .imagen {\r\n"
			+ "            width: 50px; /* Ancho de la imagen */\r\n"
			+ "            height: 50px; /* Altura de la imagen */\r\n"
			+ "            border-radius: 50%; /* Hace que la imagen sea circular (opcional) */\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "    <main>\r\n"
			+ "  <h2>Muchas gracias por tu compra!</h2>\r\n"
			+ "  <h4>Aquí tienes los detalles de tu entrada:</h4>\r\n"
			+ "        <div class=\"card\">\r\n"
			+ "   <img class=\"imagen\" src=\"{imagen}\" alt=\"Imagen del evento\">\r\n"
			
			+"     <h3>Artista: {titulo}</h3>"
			+"     <h3>Lugar: {lugar}, {recinto}</h3>"
			+"     <h3>Fecha del evento: {fecha}</h3>"
			+"     <h3>Correo Electrónico: {correo}</h3>"
			+ "            <!-- Agrega más contenido según sea necesario -->\r\n"
			+ "        </div>\r\n"
			+ "    </main>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>";
}
